---
title: ""
---

<style>
header {
  color: #000000;
  background-color: #708090;
  opacity: 0.6;
  font-family: Calibri;
  font-size: 14px;
}
body {
  color: #000000;
  font-family: Calibri;
  background-color: #F5F5F5;
}
pre {
  color: #708090;
  background-color: #F8F8FF;
}
</style>

<br>

A full list of publications can be found on my [Google Scholar](https://scholar.google.com/citations?user=YCNVdw0AAAAJ&hl=en) page. Feel free to email me to request copies any of these articles.
<br>
<br>

#### JOURNAL ARTICLES

- **Hagan JG**, Gamfeldt L, Brophy C, Fanin N, Gamfeldt L, Hautier Y, Manning P, Meyer S, Slade E, Rogier F (in prep.). A guide to quantifying multifunctionality in ecology, conservation and ecosystem management.

- **Hagan JG**, Bergmann R, Snoeks J, Dolmans V, Vanschoenwinkel B (in prep). [InvTraitR: Improving biomass estimations for freshwater invertebrates using taxonomic backbones and habitat similarity](https://github.com/haganjam/FW_invert_biomass_allometry). Manuscript and R-package.

- **Hagan JG** (2023). [Compensation alters estimates of the number of species required to maintain ecosystem functioning across an emersion gradient: A case study with intertidal macroalgae](https://doi.org/10.1111/1365-2435.14487). Functional Ecology *Early view*.

- **Hagan JG**, Henn JJ, Osterman WHA (2022). [Matters Arising: Plant traits alone are good predictors of ecosystem properties when used carefully](https://doi.org/10.1038/s41559-020-01316-9). Nature Ecology and Evolution 7. Response to: van der Plas et al. (2020, Nature Ecology and Evolution). 

- **Hagan JG**, Schrofner-Brunner B, Gamfeldt L (2023, preprint). [Quantifying biodiversity effects on ecosystem functioning across space and time in natural and semi-natural ecosystems](https://doi.org/10.21203/rs.3.rs-3249429/v1). ResearchSquare.

- Gould E, … **Hagan JG**, et al. (2023, preprint). [Same data, different analysts: variation in effect sizes due to analytical decisions in ecology and evolutionary biology](https://doi.org/10.32942/X2GG62). EcoEvoRxiv.

- Gamfeldt L, **Hagan JG**, Farewell A, Palm M, Warringer J, Roger F. (2023). [Scaling-up the biodiversity–ecosystem functioning relationship: the effect of environmental heterogeneity on transgressive overyielding](https://doi.org/10.1111/oik.09652). *Oikos* 2023: e09652.

- Scrofner-Brunner B, **Hagan JG**, Cappelatti L, Hassellöv J, Wißmann M, Gamfeldt L (2023). [Macroalgae maintain growth outside their observed distributions: Implications for biodiversity-ecosystem functioning at landscape scales](https://doi.org/10.1111/1365-2745.14103). *Journal of Ecology* 111: 1362-1373.

- **Hagan JG**, Gamfeldt L, Vanschoenwinkel BJ (2021). [We should not necessarily expect positive relationships between biodiversity and ecosystem functioning in observational field data](https://doi.org/10.1111/ele.13874). *Ecology Letters* 24 (12), 2537-2548.

- Bushke FT, **Hagan JG**, Santini S, Coetzee BWT (2021). [Random population fluctuations bias the Living Planet Index](Random population fluctuations bias the Living Planet Index). *Nature Ecology and Evolution* 5: 1145–1152.

- Olofsson M, **Hagan JG**, Karlson B, Gamfeldt L (2020). [Large seasonal and spatial variation in nano- and microphytoplankton diversity along a Baltic Sea—North Sea salinity gradient](https://doi.org/10.1038/s41598-020-74428-8). *Scientific Reports* 10: 17666.

- Joseph GS, Seymour CL, Coetzee BW, Ndlovu M, Deng L, Fowler K, **Hagan JG**, Brooks BJ, Seminara JA, Foord SH. (2018). [Elephants, termites and mound thermoregulation in a progressively warmer world](https://link.springer.com/article/10.1007/s10980-018-0629-9). *Landscape Ecology* 33: 731-742.

- **Hagan JG**, Du Toit JCO, Cramer MD. (2017). [Long-term livestock grazing influences the recruitment success of epigeal termites: Insights from >75-year grazing experiment in the Karoo, South Africa](https://www.tandfonline.com/doi/abs/10.2989/10220119.2017.1314981). *African Journal of Range and Forage Science* 34: 123-132.
<br>
<br>

#### BOOK CHAPTERS

- Luypaert T, **Hagan JG**, McCarthy ML, Poti M. (2020). [Status of marine biodiversity in the Anthropocene](https://doi.org/10.1007/978-3-030-20389-4_4). In: YOUMARES9 – A Conference from and for YOUng MARine RESearchers. Leibich V, Bode M, Jungblut S (eds). Springer International Publishing.
<br>
<br>

#### SCIENCE COMMUNICATION

- Sanden O with expert commentary from **Hagan JG** (2022). [Ny studie i Science: Klimatkrisen kan orsaka massdöd till havs](https://tidningensyre.se/2022/17-maj-2022/klimatkrisen-kan-orsaka-massdod-till-havs-ny-studie-i-science/). *Syre*.

- **Hagan JG**, Cramer MD (2018). [Termites and grazers: a complex, subtle relationship](https://www.farmersweekly.co.za/agri-technology/farming-for-tomorrow/termites-grazers-complex-subtle-relationship/). *Farmer’s Weekly*.


